# steps:
    #   # Checkout code from git
    #   - checkout
    #   - run:
    #       name: Install dependencies
    #       command: |
    #         # your code here
    #         apk add --update --no-cache tar gzip nodejs npm curl aws-cli
    #   - run:
    #       name: Get backend url and Backend smoke test
    #       command: |
    #         # your code here
    #         export BACKEND_IP=$(aws ec2 describe-instances \
    #         --query "Reservations[*].Instances[*].[PublicIpAddress]" \
    #         --filters "Name=tag:Name,Value=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
    #         --output test)
    #         echo ${BACKEND_IP}

    #         export BACKEND=$(echo $BACKEND_IP | grep -o '[^ ]*$')

    #         echo $BACKEND
    #         export API_URL="http://${BACKEND}:3030"
    #         echo "API_URL=${API_URL}"

    #         echo "sleeping for 1 minute"
    #         sleep 60

    #         if curl -v "${API_URL}/api/status" | grep "ok"
    #         then
    #           return 0
    #         else
    #           return 1
    #         fi
    #   - run:
    #       name: Frontend smoke test.
    #       command: |
    #         # your code here
    #         URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"  
    #         echo ${URL} 
    #         if curl -s ${URL} | grep "Welcome"
    #         then
    #             # Change this to 0 after the job fails
    #           return 1
    #         else
    #           return 1
    #         fi
    #   # Here's where you will add some code to rollback on failure
    #   - destroy-environment
    #   - revert-migrations
    